spring:
  datasource:
    url: jdbc:h2:mem:testdb   # o jdbc:h2:mem:testdb para en memoria
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: none   # create / create-drop / validate / none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console   # URL: http://localhost:8080/h2-console
